### ISSUE TITLE
Invalid repository structure.

### ISSUE THREAD

**Issue by danmarsden** [YouSeeU/moodle-mod_bongo#45]
Many organisations use git subtrees or submodules to manage plugins - for this to work correctly the code should sit in the "root" of your repository - not inside a "bongo" folder within the repository tree.

**Comment by bckelly1** [comment]
This brings the question, which is the more likely use case; do people check plugins out as git module to their moodle or do they install from zip files?  The goal behind the current structure is to more easily build the zip file for the plugin.  It's a bit harder to programmatically create a zip file when the plugin structure is flattened.

If it's a more common use case to check out as a git structure we can certainly change the structure, but it was my understanding that zip files were more common.  I would appreciate your input please.

**Comment by bckelly1** [comment]
Your explanation makes sense, thank you for clarifying.  I'll flatten the structure.
