### ISSUE TITLE
in-efficient method of obtaining "last section"

### ISSUE THREAD

**Issue by danmarsden** [YouSeeU/moodle-mod_bongo#48]
https://github.com/YouSeeU/moodle-mod_bongo/blob/master/bongo/locallib.php#L410
I haven't looked at why this is required, but it would be better to make a single sql call that returned the last section value instead of returning the records of all sections and iterating over each one.

**Comment by bckelly1** [comment]
Ideally I would make this all one SQL call, but different DBs have different ways of saying "get the last record".  For example, MySQL will use the LIMIT keyword, whereas SQL Server will use the TOP keyword.  Using this loop allows it to be cross-DB compatible with no special SQL code.

**Comment by danmarsden** [comment]
There are a number of ways to generate cross-db compatible sql to do this.

You could use "order by" and a limit - all of the moodle db api functions allow you to pass a limit as a parameter (not in the raw sql) which is then translated for the various db types Moodle supports.

But in this case a better option would be to use the SQL function "MAX()" which is supported by all db types as standard sql - you will also see other functions like MIN, AVG, SUM, COUNT in existing Moodle code. I'd suggest you look for existing Moodle code that uses the "MAX()" function in a sql command for an example.

Since we're talking about db functions - you should also be aware of "recordsets" - when you do have to loop over a list of records - but do not need to store the full list of records in memory - you should be using a recordset - eg:
```
$records = $DB->get_recordset("users");
foreach ($users as $user) {
  // do something.
}
$records->close();
```
You need to make sure you close the recordset when you're done with it - but this is a lot more efficient than using a normal get_records() call because it doesn't load the full list into memory.

I'd also recommend you read and bookmark this page which documents a number of helper functions that can be used to generate cross-db compatible sql.
https://docs.moodle.org/dev/Data_manipulation_API
